/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StudentFaucet } from "./StudentFaucet";

export { StudentFaucet__factory } from "./factories/StudentFaucet__factory";
